trigger:
  paths:
    include:
      - Zooper.Effortless.ASP.Validation.FluentValidation/**
  branches:
    include:
      - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  majorMinorVersion: 1.0
  semanticVersion: $[counter(variables['majorMinorVersion'], 0)]
  projectName: Zooper.Effortless.ASP.Validation.FluentValidation

name: $(majorMinorVersion).$(Rev:r)

extends:
  template: Templates/template_nuget_build_and_push.yaml
  parameters:
    projectName: $(projectName)
    buildConfiguration: $(buildConfiguration)