trigger: none
pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  nugetConfigPath: '$(System.DefaultWorkingDirectory)/nuget.config'

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 8.0'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'
      includePreviewVersions: true
    
    # Install Nuget
  - task: NuGetToolInstaller@1
    inputs:
      versionSpec:
      checkLatest: true

  # Restore all projects Nuget packages
  - task: DotNetCoreCLI@2
    displayName: 'NuGet restore'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'config'
      nugetConfigPath: '${{ parameters.nugetConfigPath }}'
  
  # Build the project
  - task: DotNetCoreCLI@2
    displayName: 'Build all projects'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration ${{ parameters.buildConfiguration }}'
  
  # Run tests here if any exist
  - script: dotnet test
    displayName: 'Run Unit Tests'