name: Publish NuGet Package for ZEA.Architecture.Patterns.StrongTypes.Generator

on:
  push:
    branches:
      - main
      - develop
    paths:
      - '**/ZEA.Architecture.Patterns.StrongTypes.Generator/**'

  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      projectName: ZEA.Architecture.Patterns.StrongTypes.Generator

    steps:
      - uses: actions/checkout@v3

      # Use the get-csproj-version action to extract the version
      - name: Get .csproj Version
        id: get_version
        uses: KageKirin/get-csproj-version@v0
        with:
          file: 'Architecture/Patterns/StrongTypes/ZEA.Architecture.Patterns.StrongTypes.Generator/ZEA.Architecture.Patterns.StrongTypes.Generator.csproj'

      # Echo the semantic version to verify it's correct
      - name: Echo the semantic version
        run: |
          echo "Extracted Semantic version: ${{ steps.get_version.outputs.version }}"
          echo "VERSION=${{ steps.get_version.outputs.version }}" >> $GITHUB_ENV
          echo "PROJECT_PATH=Architecture/Patterns/StrongTypes/ZEA.Architecture.Patterns.StrongTypes.Generator/ZEA.Architecture.Patterns.StrongTypes.Generator.csproj" >> $GITHUB_ENV

      # Call the reusable NuGet Build and Push workflow
      - name: Call NuGet Build and Push Template
        uses: ./.github/workflows/template_nuget_build_and_push.yml@develop
        with:
          projectPath: ${{ env.PROJECT_PATH }}
          buildConfiguration: Release
          semanticVersion: ${{ env.VERSION }}
          isPreRelease: ${{ github.ref != 'refs/heads/main' }}
          buildVersion: ${{ github.run_number }}