name: Publish NuGet Package

on:
  push:
    branches:
      - main
      - develop
    paths:
      - '**/ZEA.Architecture.Patterns.StrongTypes.Generator/**'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Get the version from the csproj file
      - name: Get .csproj Version
        id: get_version
        uses: KageKirin/get-csproj-version@v0
        with:
          file: 'Architecture/Patterns/StrongTypes/ZEA.Architecture.Patterns.StrongTypes.Generator/ZEA.Architecture.Patterns.StrongTypes.Generator.csproj'

      - name: Call NuGet Build and Push Template
        uses: ./.github/workflows/nuget_build_and_push.yml
        with:
          projectPath: 'Architecture/Patterns/StrongTypes/ZEA.Architecture.Patterns.StrongTypes.Generator/ZEA.Architecture.Patterns.StrongTypes.Generator.csproj'
          semanticVersion: ${{ steps.get_version.outputs.version }}
          isPreRelease: ${{ github.ref != 'refs/heads/main' }}
          buildVersion: ${{ github.run_number }}