name: Publish NuGet Package

on:
  push:
    branches:
      - main
      - develop
    paths:
      - '**/ZEA.Architecture.Patterns.StrongTypes.Generator/**'
      
  workflow_dispatch:

jobs:
  publish-package:
    uses: ./.github/workflows/nuget_build_and_publish.yml
    with:
      projectPath: 'Architecture/Patterns/StrongTypes/ZEA.Architecture.Patterns.StrongTypes.Generator/ZEA.Architecture.Patterns.StrongTypes.Generator.csproj'
      isPreRelease: ${{ github.ref != 'refs/heads/main' }}
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}