name: NuGet Build and Publish

on:
  workflow_call:
    inputs:
      projectName:
        type: string
        required: true
      buildConfiguration:
        type: string
        default: 'Release'
      isPreRelease:
        type: boolean
        required: true
    secrets:
      NUGET_API_KEY:
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      # Find the .csproj file by project name
      - name: Find .csproj file
        id: find_csproj
        run: |
          echo "Searching for .csproj file named '${{ inputs.projectName }}.csproj' in the repository..."
          CS_PROJ_PATH=$(find . -type f -name "${{ inputs.projectName }}.csproj" -print -quit)
          if [ -z "$CS_PROJ_PATH" ]; then
            echo "Error: No .csproj file named '${{ inputs.projectName }}.csproj' found in the repository."
            exit 1
          fi
          echo "Found .csproj file at: $CS_PROJ_PATH"
          echo "projectPath=$CS_PROJ_PATH" >> $GITHUB_OUTPUT
          echo "PROJECT_PATH=$CS_PROJ_PATH" >> $GITHUB_ENV

      # Extract version from the .csproj file
      - name: Get .csproj Version
        id: get_version
        uses: KageKirin/get-csproj-version@v0
        with:
          file: ${{ steps.find_csproj.outputs.projectPath }}

      # Set package version
      - name: Set package version
        id: versioning
        run: |
          echo "Base semantic version: ${{ steps.get_version.outputs.version }}"
          if [ "${{ inputs.isPreRelease }}" == "true" ]; then
            if [[ "${{ steps.get_version.outputs.version }}" == *"-"* ]]; then
              echo "PACKAGE_VERSION=${{ steps.get_version.outputs.version }}.${{ github.run_number }}" >> $GITHUB_ENV
            else
              echo "PACKAGE_VERSION=${{ steps.get_version.outputs.version }}-preview.${{ github.run_number }}" >> $GITHUB_ENV
            fi
          else
            echo "PACKAGE_VERSION=${{ steps.get_version.outputs.version }}" >> $GITHUB_ENV
          fi

      # Set up .NET Core
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore "$PROJECT_PATH"

      # Build the project with the correct versioning
      - name: Build the project
        run: dotnet build "$PROJECT_PATH" --configuration "${{ inputs.buildConfiguration }}" /p:PackageVersion="${{ env.PACKAGE_VERSION }}"

      # Pack the NuGet package
      - name: Pack the NuGet package
        run: dotnet pack "$PROJECT_PATH" --configuration "${{ inputs.buildConfiguration }}" /p:PackageVersion="${{ env.PACKAGE_VERSION }}"

      # Publish the NuGet package
      - name: Publish to NuGet
        run: dotnet nuget push **/*.nupkg --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json