name: Nuget-Push

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      buildConfiguration: 'Release'
      nugetConfigPath: './nuget.config'

    steps:

      # Check out the code
      - uses: actions/checkout@v2
        
      # Use the latest .Net version
      - name: 'Use .NET Core sdk 8.0'
        uses: actions/setup-dotnet@v1
        with:
          version: '8.0.x'
          include-prerelease: true
        
      # Restore NuGet packages
      - name: Restore NuGet packages
        run: | 
          find . -name '*.csproj' -exec dotnet restore {} \;
      
      # Build the project
      - name: Build
        run: |
          find . -name '*.csproj' -exec dotnet build {} --configuration ${{ env.buildConfiguration }} --no-restore \;
        
      # Upload the build artifacts
      - name: Upload build outputs and project files
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-artifacts
          path: |
            **/bin/${{ env.buildConfiguration }}/net8.0/**
            **/*.csproj
          
  package:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      # Download the build artifacts
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: dotnet-artifacts
          path: artifacts
      
      # Setup .Net 8 SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      # Pack the packages
      - name: Pack projects
        run: |
          find artifacts -name '*.csproj' -exec dotnet pack {} --no-build --configuration ${{ env.buildConfiguration }} --output ./nupkgs \;